### ISSUE TITLE
Formatting readable string outputs

### ISSUE THREAD

**Issue by kzlsahin** [iremssntrk/Test#1]
This issue is not important in terms of running software.  I just want to share a knowledge that is hard to find out and is very easy to be unaware of when needed. Here is the issue just like a tutorial:

When a bunch of data is required to be written in a plain text, the most important part of chosing the right format is considering how the output will be consumed. If the output will be consumed by another application, then the output is better orginized with single character splitters like ',' or ';'.  However, if the output will be consumed by human, I mean, if the readability is the number one consideration, then, the output is better to be seperated by spaces, just like you did.

Write("[B]        [L]        [T]          [Cb]        [Δ]");

And yet, there is a better way. If the output which consist of rows and coloums is most readible if it has tabular format. There is an easy method in C# to format outputs in this way.

I guess you already know the string interpolation concept using dolar sign and curly brackets: $"hi {irem}, just like tihs".

And you can format the interpolation like in the example below:
Console.Write($"B: {B, -20:f} L: {c, -20:f} T: [{T, -20:f}  Cb: {Cb, -20:f}");

Here the statement in the curly brackets is called composite formatting. for example, let's consider {B, -20:f}:
- B is the name of the variable of which value will be converted to string and put into the position inside the wrapping string,
- -20 tells the formatter that we will spare 20 character long space for the varialbe B and the variable B will be positioned on the left. (if it was 20 or +20, the variable would be aligned to the right),
- :f means the variable will be formatted as a floating-point number

You may use this method in the MarineParamCalculator, or just close the issue after you read.

kind reagards,

further reading:
https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting

**Comment by iremssntrk** [comment]
Thank you for your this feedback. I applied this formatted string on project as you said.

kind regards,
